<?php
require_once 'db.php';
include 'header.php';
$pageTitle = 'main page';
?>


    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nunc neque, dictum quis rutrum sit amet, tincidunt eu nulla. Pellentesque elementum massa vitae pharetra viverra. Nulla tempor at lorem quis pulvinar. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur lobortis tincidunt est tincidunt elementum. Donec feugiat eu ligula non feugiat. Suspendisse vel ligula vehicula, mollis felis et, venenatis nisi. Suspendisse malesuada metus rhoncus nisi maximus, at fermentum libero aliquam. Curabitur commodo mattis volutpat. Nullam eu mi a elit venenatis bibendum sit amet in ligula. Nunc tempor ante purus, sit amet dignissim eros porta sed. Vivamus feugiat turpis eget dapibus sodales. Proin faucibus, felis vel sollicitudin mattis, nulla velit ullamcorper arcu, ut finibus est ligula ut erat. Donec pellentesque egestas lorem eu facilisis. Nam non feugiat felis, vitae ultrices enim. Aenean odio urna, congue vel iaculis non, varius pretium metus.

    Mauris in varius ex. Etiam et dolor dapibus, interdum purus vitae, ornare purus. Suspendisse orci turpis, rutrum euismod elit non, pretium posuere nisl. Etiam pulvinar suscipit lacus pellentesque auctor. Cras porta arcu eget lacus interdum dictum. Vivamus fringilla libero quis mauris viverra viverra. Etiam non diam id metus vestibulum condimentum. Nam volutpat est nisi, vitae tincidunt mi pulvinar quis. Ut sed porta tortor. Duis ut rutrum lacus, a mollis eros. Curabitur lacinia dapibus lectus, auctor bibendum libero ornare sit amet. Etiam eu ligula lacus. Vestibulum magna augue, tincidunt eget facilisis non, dapibus id augue. Quisque nec risus auctor, pharetra lacus nec, commodo mi.

    Ut luctus nisi risus, ultrices pellentesque erat feugiat id. In nunc nibh, laoreet ac ornare id, euismod eget ante. Ut mauris risus, tincidunt eget urna eu, aliquam hendrerit elit. Fusce efficitur, velit ac maximus tempor, metus metus congue justo, eu convallis velit nunc at neque. Aenean et lacus id risus consectetur volutpat at in justo. Donec pharetra urna vel vehicula maximus. Ut et mauris quis erat sagittis pharetra. Nullam sit amet ipsum sed justo blandit finibus id et nulla. Integer et nisi feugiat, posuere felis ac, tristique quam. Cras vel dignissim sem, vitae hendrerit leo. Morbi a lacus imperdiet, gravida ipsum eget, maximus tortor. Sed elementum lorem in nisl tristique auctor. Morbi venenatis est in augue elementum, efficitur egestas erat facilisis. Nulla felis elit, viverra sed mollis vel, egestas in nunc. Duis sodales pharetra lectus, non vulputate tortor feugiat eget. Suspendisse potenti.

    Praesent at volutpat mi. Curabitur sapien lectus, posuere finibus libero eu, finibus pretium sapien. Nullam in felis id neque ullamcorper facilisis. Aliquam libero dui, porta id tellus vel, condimentum mattis ante. Ut et libero sodales, rutrum ante ut, molestie nisi. Pellentesque congue lorem at magna congue, non facilisis risus gravida. Vivamus tempor ornare velit, nec ultricies massa fermentum et. Ut est magna, ornare ut elit vel, molestie finibus massa. Pellentesque sit amet aliquet felis, et sollicitudin nisl. Maecenas eros massa, bibendum in tristique ut, accumsan at ante. Proin lobortis velit sollicitudin tellus varius, sit amet tristique massa hendrerit. Sed tristique eget metus in ullamcorper. Vivamus rutrum erat id libero euismod, ac dapibus nunc malesuada. Donec elementum urna consectetur justo tempus, a malesuada erat feugiat. Nulla et sodales eros. Pellentesque sollicitudin elit quis eleifend volutpat.

    Maecenas sollicitudin justo nec dolor commodo rhoncus. Donec commodo, risus at convallis pretium, mauris nunc ultrices lectus, id posuere neque mi venenatis turpis. Nulla aliquam orci in nisi dictum, cursus porta urna imperdiet. Aliquam venenatis imperdiet consequat. Maecenas vitae elit nec nibh vulputate iaculis non sed massa. Nulla facilisi. Aliquam sed odio nec nunc pellentesque dictum consectetur in ex. Ut quis metus vel ipsum semper blandit id et sapien.</p>

<?php
include 'footer.php';
